from datetime import datetime

from sqlalchemy import DateTime, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDMixin


class ScoutingReport(Base, UUIDMixin, TimestampMixin):
    """Scouting report generated by Gemini deep research.

    Reports are cached and shared across all users.
    The player_name_normalized field is used for cache lookups.
    """

    __tablename__ = "scouting_reports"

    # Player identification
    player_name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
    )
    player_name_normalized: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        unique=True,
    )

    # Report content
    summary: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    recent_stats: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    injury_status: Mapped[str] = mapped_column(
        String(200),
        nullable=False,
    )
    fantasy_outlook: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    detailed_analysis: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )

    # Metadata
    sources: Mapped[list] = mapped_column(
        JSONB,
        nullable=False,
        default=list,
    )
    token_usage: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        default=dict,
    )
    expires_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        index=True,
    )
